# Generated by Django 3.1.4 on 2021-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='career',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='github'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(default=1, verbose_name='仕事'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='名前'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='subimage',
            field=models.ImageField(default=1, upload_to='images', verbose_name='サブ画像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='サブタイトル'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='profile',
            name='topimage',
            field=models.ImageField(default=1, upload_to='images', verbose_name='トップ画像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter'),
        ),
    ]
